import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppShell from "./src/components/AppShell";
import { ClientProviders } from "./src/components/ClientProviders";
import CookieConsentBanner from "./src/components/CookieConsentBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProviders>
          <AppShell>{children}</AppShell>
          <CookieConsentBanner />
        </ClientProviders>
      </body>
    </html>
  );
}